name: Orchestra Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  run_snowflake:
    name: Orchestra Deploy Staging Snowflake
    runs-on: macos-latest

    env:
      ORCHESTRA_ORG_ID:  b7d69458-648e-4d4e-a094-1d4b807610bc
      DBT_PROJECT_ID: 283328
      DBT_PR_JOB_ID: 565266
      DBT_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
      DBT_JOB_CAUSE: "GitHub Actions Request"
      DBT_JOB_BRANCH: staging

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install uv
      - name: Install deps
        run: uv pip install -r requirements.txt --system
      - name: Run Orchestra job
        run: python3 .github/workflows/scripts/orchestra_workflow.py

  run_bigquery:
    name: Orchestra Deploy Staging BigQuery
    runs-on: macos-latest

    env:
      ORCHESTRA_ORG_ID:  b7d69458-648e-4d4e-a094-1d4b807610bc
      DBT_PROJECT_ID: 275557
      DBT_PR_JOB_ID: 560539
      DBT_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
      DBT_JOB_CAUSE: "GitHub Actions Request"
      DBT_JOB_BRANCH: staging

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install uv
      - name: Install deps
        run: uv pip install -r requirements.txt --system
      - name: Run Orchestra job
        run: python3 .github/workflows/scripts/orchestra_workflow.py

  run_postgres:
    name: Orchestra Deploy Staging Postgres
    runs-on: macos-latest

    env:
      ORCHESTRA_ORG_ID:  b7d69458-648e-4d4e-a094-1d4b807610bc
      ORCHESTRA_PIPELINE_ID: 127328
      DBT_PR_JOB_ID: 577883
      DBT_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
      DBT_JOB_CAUSE: "GitHub Actions Request"
      DBT_JOB_BRANCH: staging

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install uv
      - name: Install deps
        run: uv pip install -r requirements.txt --system
      - name: Run Orchestra job
        run: python3 .github/workflows/scripts/orchestra_workflow.py
